[projects.Port7]
description = "An all-in-one platform for web-based games."
url = "https://github.com/miapolis/port7"
languages = ["Elixir", "TypeScript"]

[projects.Brix]
description = "A CLI tool for scaffolding and code generation."
url = "https://crates.io/crates/brix"
languages = ["Rust"]

[projects.Stratepig]
description = "A multiplayer Stratego implementation."
url = "https://github.com/miapolis/stratepig-server"
languages = ["Rust", "C#"]
