import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import { useParallax } from "react-scroll-parallax";
import FirstSection from "../modules/sections/first";
import SecondSection from "../modules/sections/second";

const Home: NextPage = () => {

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div
        style={{
          height: "300vh",
        }}
      >
        <FirstSection />
        <SecondSection />
      </div>
    </>
  );
};

export default Home;
